version: v2beta1
name: sub-project

pipelines:
  deploy:
    run: |-
      # this does not fail
      profiles=$(get_flag "profile")

      run_dependencies --all
      build_images --all -t ${DEVSPACE_RANDOM}
      create_deployments --all

# This is a list of `images` that DevSpace can build for this project
# We recommend to skip image building during development (devspace dev) as much as possible
images:
  sub-project:
    buildKit: {}
    image: sub-project
    dockerfile: ./Dockerfile
    skipPush: true

# This is a list of `deployments` that DevSpace can create for this project
deployments:
  sub-project:
    # This deployment uses `helm` but you can also define `kubectl` deployments or kustomizations
    helm:
      # We are deploying this project with the Helm chart you provided
      chart:
        name: component-chart
        repo: https://charts.devspace.sh
      # Under `values` we can define the values for this Helm chart used during `helm install/upgrade`
      # You may also use `valuesFiles` to load values from files, e.g. valuesFiles: ["values.yaml"]
      values:
        containers:
          - image: sub-project
